version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "campaign"
          ContainerPort: 8080
        PlatformVersion: "LATEST"
        Image1Name: "<IMAGE1_NAME>"