version: 0.2

phases:
  build:
    commands:
      - RUNID="canary-$(date +%Y%m%d-%H%M%S)"
      - EXEC_ID=$(aws stepfunctions start-execution --state-machine-arn "$STATE_MACHINE_ARN" --input "{\"mode\":\"canary\",\"job_id\":\"J1\",\"portals\":[\"legacyphoto\"],\"runId\":\"$RUNID\"}" --query executionArn --output text)
      - aws stepfunctions wait execution-succeeded --execution-arn "$EXEC_ID"